Quizzing.Web/Quizzing.Web/Controllers/QuizzesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Quizzing.Web.Data;
using Quizzing.Web.Models;
using Quizzing.Web.Utilities.Constants;
using Quizzing.Web.ViewModels.Quizzes;

namespace Quizzing.Web.Controllers
{
    public class QuizzesController : Controller
    {
        private readonly IQuizRepository _quizRepository;
        private readonly IQuestionRepository _questionRepository;

        public QuizzesController(IQuizRepository quizRepository, IQuestionRepository questionRepository)
        {
            _quizRepository = quizRepository;
            _questionRepository = questionRepository;
        }

        // GET: Quizzes
        public async Task<IActionResult> Index()
        {
            return View(await _quizRepository.GetAll());
        }

        // GET: Quizzes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest(Constants.ErrorMessages.BadRequest);
            }

            var quiz = await _quizRepository.GetById(id);

            if (quiz == null)
            {
                return NotFound(Constants.ErrorMessages.NotFound);
            }

            var questions = await _questionRepository.GetByQuizId(id);

            if (questions == null)
            {
                return NotFound(Constants.ErrorMessages.NotFoundQuestion);
            }

            var model = new DetailsQuizViewModel
            {
                Quiz = quiz,
                Questions = questions,
            };

            return View(model);
        }

        // GET: Quizzes/Create
        [Authorize(Policy = "edit")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Quizzes/Create
        [Authorize(Policy = "edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("QuizId,Title")] Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                _quizRepository.Add(quiz);

                await _quizRepository.Save();

                TempData["info"] = "The quiz title has been saved";

                return RedirectToAction(nameof(Create), "Questions", new {id = quiz.QuizId} );
            }

            return View(quiz);
        }

        // GET: Quizzes/Edit/5
        [Authorize(Policy = "edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest(Constants.ErrorMessages.BadRequest);
            }

            var quiz = await _quizRepository.GetById(id);

            if (quiz == null)
            {
                return NotFound(Constants.ErrorMessages.NotFound);
            }

            var questions = await _questionRepository.GetByQuizId(id);

            var model = new EditQuizViewModel
            {
                Quiz = quiz,
                Questions = questions
            };

            return View(model);
        }

        // POST: Quizzes/Edit/5
        [Authorize(Policy = "edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("QuizId,Title")] Quiz quiz)
        {
            if (id != quiz.QuizId)
            {
                return BadRequest(Constants.ErrorMessages.BadRequest);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _quizRepository.Update(quiz);

                    await _quizRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuizExists(quiz.QuizId))
                    {
                        return NotFound(Constants.ErrorMessages.NotFound);
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["info"] = "The quiz title has been updated";

                return RedirectToAction(nameof(Edit));
            }

            return View();
        }

        // GET: Quizzes/Delete/5
        [Authorize(Policy = "edit")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest(Constants.ErrorMessages.BadRequest);
            }

            var quiz = await _quizRepository.GetById(id);
                
            if (quiz == null)
            {
                return NotFound(Constants.ErrorMessages.NotFound);
            }

            return View(quiz);
        }

        // POST: Quizzes/Delete/5
        [Authorize(Policy = "edit")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quiz = await _quizRepository.GetById(id);

            _quizRepository.Remove(quiz);

            await _quizRepository.Save();

            TempData["info"] = "The quiz has been deleted";


            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "edit")]
        private bool QuizExists(int id)
        {
            return _quizRepository.QuizExists(id);
        }
    }
}

Quizzing.Web/Quizzing.Web/Views/Shared/AccessDenied.cshtml
<div class="text-center">
    <h1 class="text-danger">Access Denied</h1>
    <h6 class="text-danger">You do not have permission to view this resource.</h6>
</div>

Quizzing.Web/Quizzing.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quizzing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">Quizzing</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Quizzes" asp-action="Index">List of Quizzes</a>
                            </li>
                        }
                        @*If role is "admin*@
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("edit"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Quizzes" asp-action="Create">Add Quiz</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-row-reverse">
                        @if (signInManager.IsSignedIn(User))
                        {
                        <li class="nav-item">
                            @*- Post action to logout the user to avoid malicious acts*@
                            <form method="post" asp-controller="Account" asp-action="logout">
                                <button type="submit" class="nav-link btn btn-link py-0">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2021 - Quizzing
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>